### ISSUE TITLE
Tạo trang index với header footer

### ISSUE THREAD

**Issue by PhamHongQuan** [PhamHongQuan/Ecommerce-Web#1]
@NguyenNhatTruong63

**Comment by NguyenNhatTruong63** [comment]
ok

**Comment by NguyenNhatTruong63** [comment]
header: tên shop, trang chủ, danh sách, giỏ hàng, tài khoản
footer: tên shop, thông tin cửa hàng, danh sách sản phẩm, chính sách, khách hàng
index: ảnh sản phẩm, tên sản phẩm, giá, tin mới nhất, thương hiệu nổi tiếng
